import type { Supplier } from "../types/supplierType";

export const dummySuppliers: Supplier[] = [
    {
        id: "sup-001",
        name: "Acme Textiles",
        contactEmail: "info@acme.com",
        contactPhone: "+46 8 123 456",
        address: "Kungsgatan 1, Stockholm",
        productsCount: 10,
    },
    {
        id: "sup-002",
        name: "Nordic Shoes AB",
        contactEmail: "support@nordicshoes.se",
        contactPhone: "+46 31 234 567",
        address: "Göteborgsvägen 45, Göteborg",
        productsCount: 10,
    },
    {
        id: "sup-003",
        name: "OutdoorPro",
        contactEmail: "sales@outdoorpro.eu",
        contactPhone: "+46 90 333 222",
        address: "Skogsvägen 77, Umeå",
        productsCount: 10,
    },
    {
        id: "sup-004",
        name: "FitnessGear",
        contactEmail: "kontakt@fitnessgear.se",
        contactPhone: "+46 8 555 123",
        address: "Sveavägen 100, Stockholm",
        productsCount: 10,
    },
    {
        id: "sup-005",
        name: "GastroTools",
        contactEmail: "order@gastrotools.dk",
        contactPhone: "+45 70 700 700",
        address: "København V, Danmark",
        productsCount: 10,
    },
    {
        id: "sup-006",
        name: "TrendMode",
        contactEmail: "fashion@trendmode.com",
        contactPhone: "+46 40 123 789",
        address: "Malmö Fashion Center",
        productsCount: 10,
    },
    {
        id: "sup-007",
        name: "Ljus & Dekor",
        contactEmail: "info@ljusdekor.se",
        contactPhone: "+46 18 765 432",
        address: "Storgatan 22, Uppsala",
        productsCount: 10,
    },
    {
        id: "sup-008",
        name: "KidsZone",
        contactEmail: "hello@kidszone.toys",
        contactPhone: "+46 60 123 321",
        address: "Barnens gata 12, Sundsvall",
        productsCount: 10,
    },
    {
        id: "sup-009",
        name: "TechStash",
        contactEmail: "support@techstash.se",
        contactPhone: "+46 20 404 404",
        address: "Teknikvägen 99, Lund",
        productsCount: 10,
    },
    {
        id: "sup-010",
        name: "Bokhörnan",
        contactEmail: "kontakt@bokhornan.se",
        contactPhone: "+46 10 505 101",
        address: "Biblioteksgatan 8, Växjö",
        productsCount: 10,
    },
];
